import { Menu } from '@headlessui/react'
import Cookies from 'js-cookie'
import { signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'
import React, { useContext, useEffect, useState } from 'react'
import { ToastContainer } from 'react-toastify'
import { Store } from '../utils/Store'
import DropdownLink from './DropdownLink'

export default function Layout({ title, children }) {
  const { state, dispatch } = useContext(Store)
  const { cart } = state
  const { status, data: session } = useSession()

  const [cartItemsCount, setCartItemsCount] = useState(0) //변수 1을 변형시키는 변수2, 카트 대소문자 구분
  useEffect(() => {
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0))
  }, [cart.cartItems])

  const logoutClickHandler = () => {
    Cookies.remove('cart')
    dispatch({ type: 'CART_RESET' })
    signOut({ callbackUrl: '/login' })
  }

  return (
    <div>
      <>
        <Head>
          <title> {title ? title + ' - NextMall' : 'NextMall'} </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <ToastContainer position="bottom-center" limit={1} />
        <div className="flex flex-col h-screen justify-between">
          <header>
            <nav className="flex justify-between items-center bg-fuchsia-200 h-12 px-4 shadow-md">
              <Link href="/">
                <a className="text-lg font-bold">NextMall</a>
              </Link>
              <div>
                <Link href="/cart">
                  <a className="p-2">
                    cart
                    {cartItemsCount > 0 && (
                      <span className="ml-1 rounded-full bg-red-600 px-2 text-xs py-1 ">
                        {cartItemsCount}
                      </span>
                    )}
                  </a>
                </Link>

                {status === 'loading' ? (
                  'Loading'
                ) : session?.user ? (
                  <Menu as="div" className="relative inline-block">
                    <Menu.Button className="text-blue-600">
                      {session.user.name}
                    </Menu.Button>
                    <Menu.Items className="absolute right-0 w-56 origin-top-right bg-white  shadow-lg ">
                      <Menu.Item>
                        <DropdownLink className="dropdown-link" href="/profile">
                          Profile
                        </DropdownLink>
                      </Menu.Item>
                      <Menu.Item>
                        <DropdownLink
                          className="dropdown-link"
                          href="/order-history"
                        >
                          Order History
                        </DropdownLink>
                      </Menu.Item>
                      <Menu.Item>
                        <a
                          className="dropdown-link"
                          href="#"
                          onClick={logoutClickHandler}
                        >
                          Logout
                        </a>
                      </Menu.Item>
                    </Menu.Items>
                  </Menu>
                ) : (
                  <Link href="/login">
                    <a className="p-2">Login</a>
                  </Link>
                )}

                {/* <Link href="/login">
                  <a className="p-2">Login</a>
                </Link> */}
                <Link href="/intro">
                  <a className="p-2">intro</a>
                </Link>
              </div>
            </nav>
          </header>

          <main className="container m-auto mt-4 px-4">{children}</main>
          <footer className="flex h-10 bg-slate-100 justify-center items-center shadow-inner">
            <p> Copyright &copy; 2022 </p>
          </footer>
        </div>
      </>
    </div>
  )
}
